mutation CreateTodoForUser($input: NewTodoInput!) {
  newTodo(input: $input) {
    name
    done
    user {
      username
    }
  }
}

# query params
# {
#   "input": {
#     "name": "clean room",
#     "type": "reminder",
#     "user": "1"
#   }
# }